## Programming Lab #2
## Foundations of Machine Learning

The purpose of this project is to build predictive algorithms that predict the likelihood a person has a stroke. The data include:
  
  - `age`: Patient age, numeric
  - `avg_glucose_level`: Blood sugar levels, numeric
  - `bmi`: Body mass index, numeric
  - `ever_married`: Ever married, dummy/character (Yes, No)
  - `gender`: Male, Female, or Other, character
  - `heart_disease`: Has heart disease, dummy
  - `hypertension`: Has hypertension, dummy
  - `id`: Study identification number
  - `Residence_type`: Type of residence, dummy/character (Urban, Rural)
  - `smoking_status`: Former, never, or current smoker, categorical
  - `work_type`: Employment type (Never worked (Never_worked), homemaker ("children"), Public sector employment (Govt_job), Private sector employment (`Private`), Self-employed (`Self-employed`)
  - `stroke`: Suffered a stroke in the sample period
  
The data come in two files: `training_data.csv`, which you should use to build your models, and `testing_data.csv`, which you should use to test your models. The models must be trained on the training data and tested on the testing data, but providing both files allows you to experiment with your choices and iterate on model designs. If performance drops on the testing data, you know there's a problem.
  
You can use any of the tools presented in class: $k$ nearest neighbor, linear models, or decision trees. In principle, $k$ means clustering might also be helpful for looking for patterns in the data that the other methods might miss. Using canned versions of more advanced tools (boosting, bagging, random forests, neural networks, etc.) is deeply unsporting and thus not allowed. You can be creative about transforming variables, or combining decision trees with linear models or $k$NN. Try something interesting. Fail extravagantly. The goal is to work on an intellectually interesting question that is similar to the tasks that data scientists are called on to do every day.
  
We will compare the groups' models to see if there are common trends or significant differences, and also to declare **The Winners** on the basis of whichever team achieves the lowest $RMSE$ on the testing data. A simple linear model with some polynomials and dummy variables achieves an $R^2$ of .087 and a $RMSE$ of .206.

In [2]:
import pandas as pd
import numpy as np
df_train = pd.read_csv('https://raw.githubusercontent.com/DS3001/group22/main/project_2/data/testing_data.csv')
df_test = pd.read_csv('https://raw.githubusercontent.com/DS3001/group22/main/project_2/data/training_data.csv')

y_train = df_train['stroke']
X_train = df_train.drop('stroke',axis=1)
y_test = df_test['stroke']
X_test = df_test.drop('stroke',axis=1)

X_train['bmi'] = X_train['bmi'].fillna(X_train['bmi'].mean())
X_test['bmi'] = X_test['bmi'].fillna(X_test['bmi'].mean())

In [ ]:
## Linear Model
from sklearn.linear_model import LinearRegression # Import linear regression model
from sklearn.preprocessing import PolynomialFeatures

X_train_numeric = X_train.loc[:,['age','hypertension','heart_disease','bmi','avg_glucose_level'] ]
#
expander = PolynomialFeatures(degree=2,include_bias=False) # Create the expander
Z = expander.fit_transform(X_train_numeric) # Pass the df into the expander to get powers/interactions of x and y
names = expander.get_feature_names_out() # Get the names of these variables
continuous = pd.DataFrame(data=Z, columns = names) # Create a new, expanded dataframe
#
dummies = pd.concat([ pd.get_dummies(X_train['work_type'],dtype='int',drop_first=True),
                      pd.get_dummies(X_train['Residence_type'],dtype='int',drop_first=True),
                      pd.get_dummies(X_train['smoking_status'],dtype='int',drop_first=True)],axis=1)
#
Z_train = pd.concat([continuous,dummies],axis=1)

X_test_numeric = X_test.loc[:,['age','hypertension','heart_disease','bmi','avg_glucose_level'] ]
#
expander = PolynomialFeatures(degree=2,include_bias=False) # Create the expander
Z = expander.fit_transform(X_test_numeric) # Pass the df into the expander to get powers/interactions of x and y
names = expander.get_feature_names_out() # Get the names of these variables
continuous = pd.DataFrame(data=Z, columns = names) # Create a new, expanded dataframe

dummies = pd.concat([ pd.get_dummies(X_test['work_type'],dtype='int',drop_first=True),
                      pd.get_dummies(X_test['Residence_type'],dtype='int',drop_first=True),
                      pd.get_dummies(X_test['smoking_status'],dtype='int',drop_first=True)],axis=1)
#
Z_test = pd.concat([continuous,dummies],axis=1)

# Fit the model and get the R2 measure:
reg = LinearRegression().fit(Z_train, y_train) # Fit the linear model
print('R2: ', reg.score(Z_test, y_test)) # R squared measure
y_hat = reg.predict(Z_test)
N = len(y_test)
print('RMSE: ', (np.sum( (y_test - y_hat)**2)/N )**.5 )   # R squared measure


R2:  0.08717964343843831
RMSE:  0.20599583849613765


This is supposed to be fairly "fun," so please do not turn it into a combinatorial nightmare of comparing thousands of model specifications. Settle on a strategy you think is promising, crank it out, and write up the results. Your time and energy are valuable, so learn to recognize when the marginal cost of another twenty minutes on a project exceeds the benefit in terms of improving the results and your grade.
  
## Paper format

The format of the paper should be:

  - Summary: A one paragraph description of the question, methods, and results (about 350 words).
  - Data: One to two pages discussing the data and key variables, and any challenges in reading, cleaning, and preparing them for analysis.
  - Results: Two to five pages providing visualizations, statistics, a discussion of your methodology, and a presentation of your main findings.
  - Conclusion: One to two pages summarizing the project, defending it from criticism, and suggesting additional work that was outside the scope of the project.
  - Appendix: If you have a significant number of additional plots or table that you feel are essential to the project, you can put any amount of extra content at the end and reference it from the body of the paper.

## Submission

Half of each student's grade is based on their commits to the repo. Each student is expected to do something specific that contributes to the overall project outcome. Since commits are recorded explicitly by Git/GitHub, this is observable. A student can contribute by cleaning data, creating visualizations,performing analytic analyses,  or writing about results, but everyone has to do something substantial. A student's work doesn't need to make it into the final report to be valuable and substantial, and fulfill the requirement to make a contribution to the project.

The other half of each student's grade is based on the written report. Groups will work together on combining results and writing up findings in a Jupyter noteb,ok, using code chunks to execute Python commands and markdown chunks to structure the paper and provide exposition. The notebook should run on Colab or Rivana from beginning to end without any errors.

mbers submit.

## Criteria

The project is graded based on four criteria:

  - Project Concept: What is the strategy for building and testing the group's models? How did the group decide how to use the tools presented so far in class? How did the group compare the performance of the options considered, and settle on a final choice for submission?
  - Wrangling, EDA, and Visualization: How are are missing values handled? For variables with large numbers of missing values, to what extent do the data and documentation provide an explanation for the missing data? If multiple data sources are used, how are the data merged? For the main variables in the analysis, are the relevant data summarized and visualized through a histogram or kernel density plot where appropriate? Are basic quantitative features of the data addressed and explained? How are outliers characterized and addressed?
  - Analysis: What are the groups' main findings? Do the tables, plots, and statistics support the conclusions? Is the research strategy carried out correctly? If the research strategy succeeds, are the results interpreted correctly and appropriately? If the research strategy fails, is a useful discussion of the flaws of the data collection process or the research strategy discussed?
  - Replication/Documentation: Is the code appropriately commented? Can the main results be replicated from the code and original data files? Are significant choices noted and explained?

Each of the four criteria are equally weighted (25 points out of 100).

# **Data Wrangling**

# age

In [8]:
var = 'age'
df_train[var].unique()

array([58.  ,  8.  , 70.  , 47.  , 74.  , 79.  , 40.  , 35.  , 44.  ,
       71.  , 23.  , 69.  , 21.  , 78.  , 24.  , 60.  , 66.  , 52.  ,
       34.  , 57.  , 41.  , 56.  ,  0.88, 25.  , 39.  , 31.  , 61.  ,
       22.  , 42.  , 33.  , 68.  , 26.  , 43.  , 53.  , 55.  , 64.  ,
       38.  ,  5.  , 54.  , 72.  , 51.  , 20.  , 65.  , 16.  , 46.  ,
       67.  , 18.  ,  1.08,  1.8 , 80.  , 37.  ,  9.  , 28.  , 10.  ,
       82.  ,  2.  , 32.  , 30.  , 45.  , 50.  ,  6.  , 73.  , 27.  ,
       63.  , 59.  , 29.  , 36.  ,  1.  , 48.  ,  1.4 , 19.  ,  1.72,
       77.  , 75.  , 15.  , 49.  , 14.  , 81.  ,  1.64, 13.  , 11.  ,
       62.  , 76.  ,  4.  , 12.  ,  7.  ,  1.48,  0.24,  0.64,  0.48,
        3.  ,  1.24, 17.  ,  1.16,  0.56,  0.72,  0.16,  1.32,  0.32])

In [13]:
df_train[var] = df_train[var].round().astype(int)

In [14]:
df_train[var].unique()

array([58,  8, 70, 47, 74, 79, 40, 35, 44, 71, 23, 69, 21, 78, 24, 60, 66,
       52, 34, 57, 41, 56,  1, 25, 39, 31, 61, 22, 42, 33, 68, 26, 43, 53,
       55, 64, 38,  5, 54, 72, 51, 20, 65, 16, 46, 67, 18,  2, 80, 37,  9,
       28, 10, 82, 32, 30, 45, 50,  6, 73, 27, 63, 59, 29, 36, 48, 19, 77,
       75, 15, 49, 14, 81, 13, 11, 62, 76,  4, 12,  7,  0,  3, 17])

# avg_glucose_level

In [15]:
var = 'avg_glucose_level'
df_train[var].unique()

array([ 87.96, 110.89,  69.04, 210.95, 205.84,  77.08,  57.08,  95.04,
        85.37,  57.33, 198.21, 149.75,  94.09, 203.04,  97.93,  78.05,
        89.44, 243.5 ,  75.23,  66.42, 205.23,  78.4 , 137.96,  72.55,
        99.8 ,  73.02,  88.11, 138.29,  83.51, 213.37, 122.41,  80.88,
        93.48, 101.37, 105.22,  68.19,  74.44,  92.21, 100.09,  75.05,
       184.15,  96.88,  79.14,  65.24, 111.19,  65.38,  96.99,  97.08,
        88.78, 102.64,  70.92,  86.11, 129.16, 114.01,  98.41, 127.18,
       105.61, 155.43,  75.29, 100.35, 247.69, 103.62, 144.1 , 114.25,
        74.46, 118.51, 182.86,  89.99,  63.61,  60.53, 102.34, 111.43,
       148.91,  69.4 ,  71.2 ,  92.04,  98.54, 112.43,  67.39,  98.42,
       111.85,  92.39,  63.71,  70.35,  57.27,  57.57,  87.43,  81.18,
        59.49,  56.75,  92.14,  92.11,  74.98,  55.25,  79.89,  94.26,
        94.34,  99.82,  59.54,  89.63,  80.93, 200.49, 156.57,  80.4 ,
        75.19, 103.51,  70.78,  84.11,  74.02,  78.49,  75.04, 128.97,
      

In [16]:
missing_values = df_train[var].isna().sum()

print(f"Number of missing values in {var}: {missing_values}")

Number of missing values in avg_glucose_level: 0


# bmi

In [17]:
var = 'bmi'
df_train[var].unique()

array([39.2, 17.6, 35.9, 50.1, 54.6, 35. , 22. , 42.4, 33. , 24.6, 27.3,
       27. , 30.9, 33.6, 31.2, 25.7, 21.9, 26.1, 29. , 23.6, 39.5, 64.8,
       35.1, 21. , 31.6, 31.1, 15.5, 26.4, 36. , 40.3, 23.8, 23.7, 37.9,
       31. , 45.2, 27.4, 22.9,  nan, 31.4, 25. , 28.9, 39.7, 41.2, 34.8,
       31.7, 35.8, 28.3, 41.6, 19. , 32.4, 31.8, 32.1, 26.7, 27.9, 22.6,
       28.1, 40.9, 27.6, 24.3, 35.6, 40.6, 24.4, 42.3, 17.5, 17. , 47.8,
       27.1, 23.1, 30.2, 36.4, 22.1, 40.5, 23. , 28. , 22.8, 55.7, 26.9,
       18.3, 36.2, 21.4, 20.4, 34.2, 42.2, 23.2, 34.6, 28.4, 57.5, 37. ,
       20.3, 22.3, 24.5, 23.5, 40.2, 29.5, 26.2, 33.3, 24.2, 23.3, 30.3,
       25.2, 36.7, 22.2, 20. , 17.8, 46.1, 33.1, 18.1, 24.8, 31.9, 25.8,
       27.7, 29.1, 30.1, 31.3, 19.5, 28.8, 32.9, 22.4, 19.8, 30.5, 42.6,
       37.1, 18.7, 32.8, 28.7, 32.3, 33.4, 44.9, 28.5, 45. , 25.3, 28.2,
       37.6, 34.4, 26.5, 21.1, 30. , 19.7, 21.8, 45.5, 21.3, 20.1, 25.1,
       42.9, 14.3, 16.2, 38.7, 29.7, 14.6, 27.2, 19

In [18]:
missing_values = df_train[var].isna().sum()

print(f"Number of missing values in {var}: {missing_values}")

Number of missing values in bmi: 42


# ever_married

In [25]:
var = 'ever_married'
df_train[var].unique()

array(['Yes', 'No'], dtype=object)

# gender

In [26]:
var = 'gender'
df_train[var].unique()

array(['Male', 'Female'], dtype=object)

# heart_disease

In [28]:
var = 'heart_disease'
df_train[var].unique()

array([0, 1])

# hypertension

In [29]:
var = 'hypertension'
df_train[var].unique()

array([1, 0])

# id

In [30]:
var = 'id'
df_train[var].unique()

array([30468, 16523, 56543, ..., 28493, 27153, 34060])

In [31]:
missing_values = df_train[var].isna().sum()

print(f"Number of missing values in {var}: {missing_values}")

Number of missing values in id: 0


# Residence_type

In [32]:
var = 'Residence_type'
df_train[var].unique()

array(['Urban', 'Rural'], dtype=object)

# smoking_status

In [33]:
var = 'smoking_status'
df_train[var].unique()

array(['never smoked', 'Unknown', 'formerly smoked', 'smokes'],
      dtype=object)

In [36]:
df_train.loc[df_train[var] == "never smoked", var] = "Non-Smoker"
df_train.loc[df_train[var] == "Unknown", var] = np.nan
df_train.loc[df_train[var] == "formerly smoked", var] = "Previous Smoker"
df_train.loc[df_train[var] == "smokes", var] = "Current Smoker"

In [37]:
var = 'smoking_status'
df_train[var].unique()

array(['Non-Smoker', nan, 'Previous Smoker', 'Current Smoker'],
      dtype=object)

# work_type

In [38]:
var = 'work_type'
df_train[var].unique()

array(['Private', 'Self-employed', 'Govt_job', 'children', 'Never_worked'],
      dtype=object)

In [39]:
df_train.loc[df_train[var] == "Private", var] = "Private Sector"
df_train.loc[df_train[var] == "Govt_job", var] = "Public Sector"
df_train.loc[df_train[var] == "children", var] = "Homemaker"
df_train.loc[df_train[var] == "Never_worked", var] = "Unemployed"

In [40]:
var = 'work_type'
df_train[var].unique()

array(['Private Sector', 'Self-employed', 'Public Sector', 'Homemaker',
       'Unemployed'], dtype=object)

# stroke

In [41]:
var = 'stroke'
df_train[var].unique()

array([0, 1])